CONFIG_GPIO=y
CONFIG_BOOTLOADER_MCUBOOT=y

CONFIG_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Activate logging to get error/warnings for SSD1306 initialization
#CONFIG_LOG=y
#CONFIG_LOG_DEFAULT_LEVEL=3

# Task Configuration
CONFIG_NUM_TASKS=3

CONFIG_TASK1_PRIORITY=1 
CONFIG_TASK1_PERIOD_MS=4000 
CONFIG_TASK1_EXECUTION_TIME_MS=2000 
CONFIG_TASK1_RELEASE_MS=0


CONFIG_TASK2_PRIORITY=2 
CONFIG_TASK2_PERIOD_MS=7000 
CONFIG_TASK2_EXECUTION_TIME_MS=2000 
CONFIG_TASK2_RELEASE_MS=0 

    
CONFIG_TASK3_PRIORITY=3 
CONFIG_TASK3_PERIOD_MS=8000 
CONFIG_TASK3_EXECUTION_TIME_MS=1000 
CONFIG_TASK3_RELEASE_MS=0

# Test Case 1
# CONFIG_TASK1_PRIORITY=1
# CONFIG_TASK1_PERIOD_MS=4000
# CONFIG_TASK1_EXECUTION_TIME_MS=500
# CONFIG_TASK1_RELEASE_MS=0

# CONFIG_TASK2_PRIORITY=2
# CONFIG_TASK2_PERIOD_MS=7000
# CONFIG_TASK2_EXECUTION_TIME_MS=1000
# CONFIG_TASK2_RELEASE_MS=0

# CONFIG_TASK3_PRIORITY=3
# CONFIG_TASK3_PERIOD_MS=8000
# CONFIG_TASK3_EXECUTION_TIME_MS=5500
# CONFIG_TASK3_RELEASE_MS=0

# Results for Test case 1: 
# Task 1 - Utl 0.125 WCS 0 TDA 0
# Task 2 - Utl 0.268 WCS 0 TDA 0
# Task 3 - Utl 0.955 WCS 8500 TDA 8500


# Test Case 2
# CONFIG_TASK1_PRIORITY=1
# CONFIG_TASK1_PERIOD_MS=3000
# CONFIG_TASK1_EXECUTION_TIME_MS=500
# CONFIG_TASK1_RELEASE_MS=0

# CONFIG_TASK2_PRIORITY=2
# CONFIG_TASK2_PERIOD_MS=5000
# CONFIG_TASK2_EXECUTION_TIME_MS=1500
# CONFIG_TASK2_RELEASE_MS=0

# CONFIG_TASK3_PRIORITY=3
# CONFIG_TASK3_PERIOD_MS=9000
# CONFIG_TASK3_EXECUTION_TIME_MS=3000
# CONFIG_TASK3_RELEASE_MS=0

# Results for Test case 2: 
# Task 1 - Utl 0.167 WCS 0 TDA 0
# Task 2 - Utl 0.467 WCS 0 TDA 0
# Task 3 - Utl 0.800 WCS 7500 TDA 8500